### ISSUE TITLE
API Management sample products have been removed

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule.Rules.Azure#344]
# Rule request

## Suggested rule change

Check API Management default products have been removed.

A new API Management instance include `starter` and `unlimited` products. Accidentally adding APIs to these sample products may expose APIs more than intended.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ApiManagement/service**

## Additional context

[Azure template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-12-01/service)

**Comment by rchithracse** [comment]
API Management sample products have been removed #344 

I am currently seeing in API management - Sample products are available . 

Would like to know ... Api Management Sample products are removed as  per the issue#344 ? So does it means "Sample products are available now right ? Could you please clarify on this.

Thanking you in advance !

**Comment by rchithracse** [comment]
API Management sample products have been removed https://github.com/Azure/PSRule.Rules.Azure/issues/344

I am currently seeing in API management - Sample products are available .

Would like to know ... Api Management Sample products are removed as per the issue#344 ? So does it means "Sample products SHOULD NOT  available now right ? Could you please clarify on this.

Thanking you in advance !
